/**
 * payment.service.js — Real Production Payment Service for KAIA Technologies.
 *
 * Architecture:
 *   Frontend → Backend (this service) → Razorpay API → Payment Response → Backend Signature Verification → Webhook → DB Update
 *
 * Production Security Rules:
 * - NEVER expose RAZORPAY_KEY_SECRET to frontend.
 * - NEVER trust frontend-provided amounts.
 * - NEVER mark payment paid without cryptographic server-side HMAC signature verification.
 * - NEVER process webhook without verifying provider HMAC signature against raw request body.
 * - NEVER create mock payment bypass or fake transactions.
 */

import {
  rupeesToPaise,
  paiseToRupees,
  validatePaymentAmount,
  verifyRazorpayPaymentSignature,
  verifyRazorpayWebhookSignature,
  generateReceiptId,
  getSafePaymentErrorMessage,
  logPaymentEvent,
} from '../../utils/paymentUtils.js';

// ---------------------------------------------------------------------------
// RAZORPAY INITIALIZATION
// ---------------------------------------------------------------------------

let _razorpayInstance = null;

/**
 * Get or initialize the active Razorpay SDK instance.
 * @returns {Promise<object>}
 */
async function getRazorpayInstance() {
  if (_razorpayInstance) return _razorpayInstance;

  const keyId = process.env.RAZORPAY_KEY_ID;
  const keySecret = process.env.RAZORPAY_KEY_SECRET;

  if (!keyId || !keySecret) {
    throw new Error('Razorpay credentials (RAZORPAY_KEY_ID / RAZORPAY_KEY_SECRET) are not configured in environment variables.');
  }

  const { default: Razorpay } = await import('razorpay');
  _razorpayInstance = new Razorpay({
    key_id: keyId,
    key_secret: keySecret,
  });

  logPaymentEvent('razorpay_initialized', { provider: 'razorpay' });
  return _razorpayInstance;
}

// ---------------------------------------------------------------------------
// CREATE PAYMENT ORDER
// ---------------------------------------------------------------------------

/**
 * Create a real Razorpay payment order.
 *
 * Steps:
 * 1. Validate the authoritative INR amount calculated from the database.
 * 2. Convert to paise for Razorpay.
 * 3. Create provider order via official Razorpay SDK.
 * 4. Return only the safe public parameters required by checkout.js.
 *
 * @param {object} params
 * @param {string} params.internalOrderId - KAIA order ID (e.g. KAIA-ORD-20260907-12345)
 * @param {number} params.amountInRupees   - AUTHORITATIVE amount from database (INR)
 * @param {string} params.currency         - Always 'INR'
 * @param {object} params.notes            - Safe metadata (no secrets)
 * @returns {Promise<object>} Safe provider order details
 */
export async function createPaymentOrder({ internalOrderId, amountInRupees, currency = 'INR', notes = {} }) {
  // 1. Authoritative Amount Validation
  const validation = validatePaymentAmount(amountInRupees);
  if (!validation.valid) {
    throw new Error(`INVALID_AMOUNT: ${validation.reason}`);
  }

  const amountInPaise = rupeesToPaise(amountInRupees);
  const receiptId = generateReceiptId(internalOrderId);

  logPaymentEvent('create_payment_order_start', {
    internalOrderId,
    amountINR: amountInRupees,
    amountPaise,
    currency,
    provider: 'razorpay',
  });

  const razorpay = await getRazorpayInstance();

  const orderOptions = {
    amount: amountInPaise,
    currency,
    receipt: receiptId,
    notes: {
      kaiaOrderId: internalOrderId,
      ...notes,
    },
  };

  const razorpayOrder = await razorpay.orders.create(orderOptions);

  logPaymentEvent('create_payment_order_success', {
    internalOrderId,
    providerOrderId: razorpayOrder.id,
    amountPaise: razorpayOrder.amount,
    status: razorpayOrder.status,
  });

  return {
    providerOrderId: razorpayOrder.id,
    amount: amountInRupees,
    amountPaise: razorpayOrder.amount,
    currency: razorpayOrder.currency,
    receipt: razorpayOrder.receipt,
    provider: 'razorpay',
    // Only public Key ID is returned — Key Secret is NEVER sent to frontend
    razorpayKeyId: process.env.RAZORPAY_KEY_ID,
  };
}

// ---------------------------------------------------------------------------
// VERIFY PAYMENT SIGNATURE
// ---------------------------------------------------------------------------

/**
 * Verify Razorpay payment signature via HMAC-SHA256 with timingSafeEqual.
 *
 * @param {object} params
 * @param {string} params.razorpayOrderId   - Razorpay order ID (order_xxx)
 * @param {string} params.razorpayPaymentId - Razorpay payment ID (pay_xxx)
 * @param {string} params.razorpaySignature - Signature generated by Razorpay Checkout
 * @returns {Promise<{ verified: boolean, method: string, failureReason: string }>}
 */
export async function verifyPaymentSignature({ razorpayOrderId, razorpayPaymentId, razorpaySignature }) {
  logPaymentEvent('verify_payment_signature_start', {
    razorpayOrderId,
    razorpayPaymentId,
    signaturePresent: !!razorpaySignature,
  });

  const keySecret = process.env.RAZORPAY_KEY_SECRET;
  if (!keySecret) {
    throw new Error('Razorpay secret key is not configured for signature verification.');
  }

  const isValid = verifyRazorpayPaymentSignature(
    razorpayOrderId,
    razorpayPaymentId,
    razorpaySignature,
    keySecret
  );

  logPaymentEvent('verify_payment_signature_result', {
    razorpayOrderId,
    razorpayPaymentId,
    verified: isValid,
  });

  return {
    verified: isValid,
    method: 'razorpay_hmac_sha256',
    failureReason: isValid ? '' : 'SIGNATURE_INVALID',
  };
}

// ---------------------------------------------------------------------------
// VERIFY WEBHOOK SIGNATURE
// ---------------------------------------------------------------------------

/**
 * Verify incoming webhook from Razorpay using HMAC-SHA256 over the raw body buffer.
 *
 * @param {Buffer} rawBody - Raw unparsed request body buffer
 * @param {string} signature - X-Razorpay-Signature header
 * @returns {boolean}
 */
export function verifyWebhookSignature(rawBody, signature) {
  const webhookSecret = process.env.RAZORPAY_WEBHOOK_SECRET;

  if (!webhookSecret) {
    logPaymentEvent('verify_webhook_secret_missing', { error: 'RAZORPAY_WEBHOOK_SECRET not configured' });
    return false;
  }

  const isValid = verifyRazorpayWebhookSignature(rawBody, signature, webhookSecret);
  logPaymentEvent('verify_webhook_signature', { valid: isValid });
  return isValid;
}

// ---------------------------------------------------------------------------
// EXTRACT WEBHOOK EVENT DATA
// ---------------------------------------------------------------------------

/**
 * Parse a Razorpay webhook payload and extract verified fields.
 * @param {object} payload - Parsed webhook body
 * @returns {{ eventId, eventType, providerOrderId, providerPaymentId, status, method, amount }}
 */
export function extractWebhookEventData(payload) {
  const eventType = payload.event || '';
  const eventId = payload.account_id
    ? `${payload.account_id}_${payload.created_at || Date.now()}`
    : `webhook_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;

  const paymentEntity = payload.payload?.payment?.entity || {};
  const orderEntity = payload.payload?.order?.entity || {};

  return {
    eventId,
    eventType,
    providerOrderId: paymentEntity.order_id || orderEntity.id || '',
    providerPaymentId: paymentEntity.id || '',
    status: paymentEntity.status || '',
    method: paymentEntity.method || '',
    amount: paymentEntity.amount ? paiseToRupees(paymentEntity.amount) : 0,
  };
}

// ---------------------------------------------------------------------------
// RESOLVE WEBHOOK ACTION
// ---------------------------------------------------------------------------

/**
 * Map verified Razorpay webhook events to application state transitions.
 *
 * @param {object} webhookData - Extracted webhook event data
 * @returns {{ action: string, paymentStatus: string, providerOrderId: string, providerPaymentId: string }}
 */
export function resolveWebhookAction(webhookData) {
  const { eventType, providerOrderId, providerPaymentId } = webhookData;

  logPaymentEvent('webhook_action_resolve', { eventType, providerOrderId });

  const eventActionMap = {
    'payment.captured': { action: 'MARK_PAID', paymentStatus: 'paid' },
    'payment.authorized': { action: 'MARK_AUTHORIZED', paymentStatus: 'authorized' },
    'payment.failed': { action: 'MARK_FAILED', paymentStatus: 'failed' },
    'order.paid': { action: 'MARK_PAID', paymentStatus: 'paid' },
    'refund.created': { action: 'MARK_REFUNDED', paymentStatus: 'refunded' },
    'refund.processed': { action: 'MARK_REFUNDED', paymentStatus: 'refunded' },
  };

  const resolved = eventActionMap[eventType] || { action: 'UNHANDLED', paymentStatus: 'pending' };

  return {
    action: resolved.action,
    paymentStatus: resolved.paymentStatus,
    providerOrderId,
    providerPaymentId,
  };
}

// ---------------------------------------------------------------------------
// INITIATE REFUND
// ---------------------------------------------------------------------------

/**
 * Initiate an authoritative refund via Razorpay API.
 *
 * @param {object} params
 * @param {string} params.paymentId - Gateway provider payment ID (pay_xxx)
 * @param {number} params.amountInRupees - Total amount to refund in INR
 * @param {object} params.notes - Safe refund reason or reference ID
 * @returns {Promise<{ providerRefundId: string, status: string, amount: number, provider: string }>}
 */
export async function initiateRefund({ paymentId, amountInRupees, notes = {} }) {
  if (!paymentId || typeof paymentId !== 'string' || !paymentId.startsWith('pay_')) {
    throw new Error('A valid Razorpay payment ID (pay_xxx) is required to initiate a refund.');
  }

  const validation = validatePaymentAmount(amountInRupees);
  if (!validation.valid) {
    throw new Error(`INVALID_REFUND_AMOUNT: ${validation.reason}`);
  }

  const amountInPaise = rupeesToPaise(amountInRupees);
  const razorpay = await getRazorpayInstance();

  try {
    const refundResponse = await razorpay.payments.refund(paymentId, {
      amount: amountInPaise,
      notes,
    });

    logPaymentEvent('razorpay_refund_success', {
      paymentId,
      refundId: refundResponse.id,
      amountPaise: refundResponse.amount,
      status: refundResponse.status,
    });

    return {
      providerRefundId: refundResponse.id,
      status: refundResponse.status || 'processed',
      amount: amountInRupees,
      provider: 'razorpay',
    };
  } catch (err) {
    const description = err.error?.description || err.message;
    logPaymentEvent('razorpay_refund_error', { paymentId, error: description });
    console.error('[PaymentService] Razorpay refund error:', description);
    throw new Error(`Razorpay gateway refund failed: ${description}`);
  }
}

export default {
  createPaymentOrder,
  verifyPaymentSignature,
  verifyWebhookSignature,
  extractWebhookEventData,
  resolveWebhookAction,
  initiateRefund,
};