import React, { useState, useEffect } from 'react';
import { 
  Landmark, DollarSign, ArrowUpRight, CheckCircle2, 
  Clock, ShieldCheck, Download, FileText, ChevronRight, X, AlertCircle 
} from 'lucide-react';
import { Link } from 'react-router-dom';
import brandSellerService from '../../services/brandSellerService';
import { Skeleton } from '../../components/feedback/Skeleton';
import Badge from '../../components/ui/Badge';
import StatusBadge from '../../components/ui/StatusBadge';
import Button from '../../components/ui/Button';

const BrandSettlements = () => {
  const [settlements, setSettlements] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedSettlement, setSelectedSettlement] = useState(null);
  const [modalLoading, setModalLoading] = useState(false);

  const fetchSettlements = async () => {
    setLoading(true);
    try {
      const res = await brandSellerService.getSettlements();
      if (res.success) {
        setSettlements(res.settlements || []);
      }
    } catch (err) {
      console.error('Error fetching settlements:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSettlements();
  }, []);

  const handleOpenDetail = async (id) => {
    setModalLoading(true);
    try {
      const res = await brandSellerService.getSettlementById(id);
      if (res.success) {
        setSelectedSettlement(res.settlement);
      }
    } catch (err) {
      alert('Error loading settlement statement details.');
    } finally {
      setModalLoading(false);
    }
  };

  return (
    <div className="space-y-6 text-left max-w-7xl mx-auto pb-16 font-sans">
      
      {/* 1. Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-brand-gray-200 pb-5">
        <div>
          <h2 className="text-xl font-black text-brand-gray-900 uppercase tracking-tight">
            Settlement Statements & Payouts
          </h2>
          <p className="text-xs text-brand-gray-500 mt-0.5">
            Periodic disbursement batches from KAIA Technologies to your brand bank account.
          </p>
        </div>

        <Link to="/brand/earnings">
          <Button variant="outline" size="sm" className="text-xs uppercase font-bold tracking-wider">
            View Live Earnings & Ledger
          </Button>
        </Link>
      </div>

      {/* 2. Settlements Table */}
      {loading ? (
        <div className="space-y-4">
          {Array(3).fill(0).map((_, i) => (
            <Skeleton key={i} className="h-8 w-full" />
          ))}
        </div>
      ) : settlements.length === 0 ? (
        <div className="bg-white border border-brand-gray-200 p-16 rounded-sm text-center shadow-premium space-y-3">
          <Landmark className="w-12 h-12 text-brand-gray-300 mx-auto" />
          <h3 className="text-base font-black text-brand-gray-900 uppercase">No settlement statements yet</h3>
          <p className="text-xs text-brand-gray-500 max-w-sm mx-auto">
            Periodic settlements are generated by marketplace finance after the standard order delivery hold period.
          </p>
        </div>
      ) : (
        <div className="bg-white border border-brand-gray-200 rounded-sm shadow-premium overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-brand-gray-200 text-left text-xs">
              <thead className="bg-brand-gray-50 uppercase tracking-wider font-bold text-[10px] text-brand-gray-500">
                <tr>
                  <th className="px-4 py-3.5">Statement ID</th>
                  <th className="px-4 py-3.5">Cycle Period</th>
                  <th className="px-4 py-3.5 text-right">Gross Sales</th>
                  <th className="px-4 py-3.5 text-right">Commission</th>
                  <th className="px-4 py-3.5 text-right">Refunds</th>
                  <th className="px-4 py-3.5 text-right">Net Disbursed</th>
                  <th className="px-4 py-3.5">Status</th>
                  <th className="px-4 py-3.5 text-right">Actions</th>
                </tr>
              </thead>

              <tbody className="bg-white divide-y divide-brand-gray-200 text-brand-gray-800">
                {settlements.map((st) => (
                  <tr key={st._id} className="hover:bg-brand-gray-50/70 transition-colors font-medium">
                    <td className="px-4 py-3.5">
                      <p className="font-mono font-bold text-brand-accent">{st.settlementNumber}</p>
                      <span className="text-[10px] text-brand-gray-400 font-mono">
                        {new Date(st.createdAt).toLocaleDateString('en-IN')}
                      </span>
                    </td>

                    <td className="px-4 py-3.5 text-[11px] text-brand-gray-600 font-mono">
                      {new Date(st.periodStart).toLocaleDateString('en-IN')} — {new Date(st.periodEnd).toLocaleDateString('en-IN')}
                    </td>

                    <td className="px-4 py-3.5 text-right font-mono font-bold text-brand-gray-900">
                      ₹{st.grossSales?.toLocaleString('en-IN')}
                    </td>

                    <td className="px-4 py-3.5 text-right font-mono text-indigo-700 font-bold">
                      -₹{st.commission?.toLocaleString('en-IN')}
                    </td>

                    <td className="px-4 py-3.5 text-right font-mono text-red-600 font-bold">
                      {st.refunds > 0 ? `-₹${st.refunds.toLocaleString('en-IN')}` : '₹0'}
                    </td>

                    <td className="px-4 py-3.5 text-right font-mono font-black text-emerald-700 text-sm">
                      ₹{st.netPayable?.toLocaleString('en-IN')}
                    </td>

                    <td className="px-4 py-3.5">
                      <StatusBadge status={st.status} />
                    </td>

                    <td className="px-4 py-3.5 text-right">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleOpenDetail(st._id)}
                        className="text-[10px] font-bold uppercase px-2 py-1 flex items-center space-x-1 ml-auto"
                      >
                        <FileText className="w-3 h-3" />
                        <span>Breakdown</span>
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* MODAL: SETTLEMENT STATEMENT BREAKDOWN                                     */}
      {/* ========================================================================= */}
      {selectedSettlement && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4">
          <div className="bg-white max-w-2xl w-full max-h-[90vh] overflow-y-auto rounded-sm shadow-2xl border border-brand-gray-200 p-6 space-y-5 text-left">
            <div className="flex justify-between items-start border-b pb-3">
              <div>
                <h3 className="text-base font-black text-brand-gray-900 uppercase">
                  Statement #{selectedSettlement.settlementNumber}
                </h3>
                <p className="text-xs text-brand-gray-500 font-mono mt-0.5">
                  Period: {new Date(selectedSettlement.periodStart).toLocaleDateString('en-IN')} to {new Date(selectedSettlement.periodEnd).toLocaleDateString('en-IN')}
                </p>
              </div>
              <button onClick={() => setSelectedSettlement(null)} className="text-brand-gray-400 hover:text-brand-gray-800">
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Financial Summary Grid */}
            <div className="grid grid-cols-4 gap-2 bg-brand-light p-4 rounded border text-xs text-center font-bold">
              <div>
                <span className="text-[10px] text-brand-gray-400 uppercase block">Gross Sales</span>
                <p className="text-brand-gray-900 mt-1 font-mono">₹{selectedSettlement.grossSales?.toLocaleString('en-IN')}</p>
              </div>
              <div>
                <span className="text-[10px] text-brand-gray-400 uppercase block">Commission</span>
                <p className="text-indigo-700 mt-1 font-mono">-₹{selectedSettlement.commission?.toLocaleString('en-IN')}</p>
              </div>
              <div>
                <span className="text-[10px] text-brand-gray-400 uppercase block">Refunds</span>
                <p className="text-red-600 mt-1 font-mono">-₹{selectedSettlement.refunds?.toLocaleString('en-IN')}</p>
              </div>
              <div>
                <span className="text-[10px] text-brand-gray-400 uppercase block">Net Payout</span>
                <p className="text-emerald-700 mt-1 font-mono text-sm font-black">₹{selectedSettlement.netPayable?.toLocaleString('en-IN')}</p>
              </div>
            </div>

            {/* Included Seller Orders */}
            <div className="space-y-2">
              <h4 className="font-bold text-xs text-brand-gray-700 uppercase tracking-wider">Included Seller Orders ({selectedSettlement.sellerOrders?.length || 0})</h4>
              <div className="border border-brand-gray-200 rounded divide-y divide-brand-gray-100 max-h-48 overflow-y-auto text-xs">
                {selectedSettlement.sellerOrders?.map((so) => (
                  <div key={so._id} className="p-3 flex justify-between items-center hover:bg-brand-gray-50">
                    <div>
                      <p className="font-mono font-bold text-brand-gray-900">{so.orderId}</p>
                      <p className="text-[10px] text-brand-gray-500 font-mono">Delivered on {new Date(so.deliveredAt || so.createdAt).toLocaleDateString('en-IN')}</p>
                    </div>
                    <div className="text-right space-y-0.5">
                      <p className="font-mono font-bold text-emerald-700">₹{so.sellerPayableAmount?.toLocaleString('en-IN')}</p>
                      <span className="text-[10px] text-brand-gray-400 font-mono">(Sale: ₹{so.finalAmount?.toLocaleString('en-IN')} - Comm: ₹{so.commissionAmount})</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="pt-3 border-t flex justify-end">
              <Button variant="outline" size="sm" onClick={() => setSelectedSettlement(null)} className="text-xs uppercase font-bold">
                Close
              </Button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default BrandSettlements;
